# Generated by Django 5.2.6 on 2025-09-22 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=50)),
                ("Email", models.CharField(max_length=50)),
                ("Address", models.CharField(max_length=50)),
                ("City", models.CharField(max_length=50)),
                (
                    "State",
                    models.CharField(
                        choices=[
                            ("GA", "Goa"),
                            ("KL", "Kerala"),
                            ("MP", "Madhya Pradesh"),
                            ("MH", "Maharashtra"),
                            ("PB", "Punjab"),
                            ("RJ", "Rajasthan"),
                            ("UP", "Uttar Pradesh"),
                            ("UK", "Uttarakhand"),
                            ("WB", "West Bengal"),
                            ("DL", "Delhi"),
                        ],
                        max_length=50,
                    ),
                ),
                ("date", models.DateField()),
            ],
        ),
    ]
