# Generated by Django 5.2.6 on 2025-09-27 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="CoffeeType",
            field=models.CharField(
                choices=[
                    ("ES", "Espresso"),
                    ("LA", "Latte"),
                    ("MO", "Mocha"),
                    ("CA", "Cappuccino"),
                    ("FW", "Flat White"),
                    ("CB", "Cold Brew"),
                ],
                default="ES",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="Instructions",
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="contact",
            name="Phone",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="contact",
            name="Quantity",
            field=models.IntegerField(default=1),
        ),
    ]
